title: "My Lanyon Blog"
email: "you@example.com"
description: "Content-first Lanyon blog"

# For project site:
url: "https://vishnupri109.github.io"
baseurl: "/my-blog"

remote_theme: poole/lanyon
plugins:
  - jekyll-remote-theme
  - jekyll-paginate

paginate: 5                 # posts per page
paginate_path: "/page:num/" # path for page 2, 3, etc.
